### ISSUE TITLE
When selecting Contract Only, no surveys should be determined

### ISSUE THREAD

**Issue by karentom** [springernature/snics-employee#106]
I selected contract only, but 4 questionnaires were assigned.

![image](https://user-images.githubusercontent.com/17595871/51297241-84f36d00-19ed-11e9-8316-7c6e6899bcc1.png)

**Comment by mohammadsiddiqui** [comment]
![image](https://user-images.githubusercontent.com/24387047/51306796-30d79f80-1a64-11e9-88f4-520b16c78058.png)

Changes are done.
@karentom please confirm

**Comment by karentom** [comment]
![image](https://user-images.githubusercontent.com/17595871/51330115-df6be800-1a44-11e9-809a-a43cd967005f.png)

Looks good!
