### ISSUE TITLE
Document section is not displaying the right answer

### ISSUE THREAD

**Issue by karentom** [springernature/snics-employee#107]
Auto extend answer was ‘No’, but it is displaying ‘Yes’.

![image](https://user-images.githubusercontent.com/17595871/51297289-aeac9400-19ed-11e9-9cff-cecb9c568c44.png)

**Comment by karentom** [comment]
@mohammadsiddiqui @harshadporwal This issue still exists. I had selected 'No for auto extend, and the answer appears as 'Yes'.

**Comment by harshadporwal** [comment]
![image](https://user-images.githubusercontent.com/43807299/51370632-c6833580-1b1d-11e9-9455-90b63808df40.png)

![image](https://user-images.githubusercontent.com/43807299/51370695-f3374d00-1b1d-11e9-81d7-0853afc19c74.png)

@karentom It is working as expected. Please try clearing history and retry.

**Comment by karentom** [comment]
tested and works.
