### ISSUE TITLE
Help texts display

### ISSUE THREAD

**Issue by karentom** [springernature/snics-employee#108]
Can we left-align the help text and use bullets for lists like we currently do on the current site? This is for all help text on the partner classification.

Current:
![image](https://user-images.githubusercontent.com/17595871/51297541-ad2f9b80-19ee-11e9-9309-bf0115df5bcb.png)

New:
![image](https://user-images.githubusercontent.com/17595871/51297559-bfa9d500-19ee-11e9-8695-7bfe05942309.png)

**Comment by harshadporwal** [comment]
![image](https://user-images.githubusercontent.com/43807299/51298956-a6d00c80-1a4c-11e9-918f-304b1db1392f.png)

Fixed and woring

**Comment by karentom** [comment]
Alignment looks good
