### ISSUE TITLE
On Select Partner page, when reviewing the assigned questionnaires, the answer below is not displaying correctly

### ISSUE THREAD

**Issue by karentom** [springernature/snics-employee#109]
I had selected the countries Albania, and Algeria in the Partner Classification.

![image](https://user-images.githubusercontent.com/17595871/51297735-90e02e80-19ef-11e9-9581-bc7b3987788e.png)

**Comment by harshadporwal** [comment]
![image](https://user-images.githubusercontent.com/43807299/51306332-1650f680-1a63-11e9-87e2-96dcc43317b5.png)

Fixed and working

**Comment by karentom** [comment]
Confirmed!
![image](https://user-images.githubusercontent.com/17595871/51330264-2d80eb80-1a45-11e9-85e3-bb5b5ce70abd.png)
