### ISSUE TITLE
Cannot invite new partner

### ISSUE THREAD

**Issue by karentom** [springernature/snics-employee#111]
Spinning circle.

![image](https://user-images.githubusercontent.com/17595871/51297922-75c1ee80-19f0-11e9-8ff8-bdfcef7212e2.png)

And then an error

![image](https://user-images.githubusercontent.com/17595871/51297945-86726480-19f0-11e9-96dc-d18f6b16c233.png)

**Comment by harshadporwal** [comment]
![image](https://user-images.githubusercontent.com/43807299/51307795-9036af00-1a66-11e9-93bd-19aa43b20fcb.png)


Fixed and working
