### ISSUE TITLE
Sponsor is not listed in matched partner search

### ISSUE THREAD

**Issue by karentom** [springernature/snics-employee#121]
In the partner search, if a partner is already in SNICS, the sponsor field should list the sponsor name. Clicking on the name would display a pop up with contact information. 

![image](https://user-images.githubusercontent.com/17595871/51335156-5ad29700-1a4f-11e9-86d6-fdbb4aa2e859.png)

This is what it looks like in the current live system.
![image](https://user-images.githubusercontent.com/17595871/51335278-aedd7b80-1a4f-11e9-83ec-7c35812b83ca.png)

![image](https://user-images.githubusercontent.com/17595871/51335297-bb61d400-1a4f-11e9-8b9a-648ccd151383.png)

**Comment by harshadporwal** [comment]
![image](https://user-images.githubusercontent.com/43807299/51366192-41425580-1b0a-11e9-9b98-533fdb0cbb7a.png)

![image](https://user-images.githubusercontent.com/43807299/51366198-4acbbd80-1b0a-11e9-8c14-a6f98d7e37a5.png)

Added sponsor details

**Comment by karentom** [comment]
Fixed. I will test.

**Comment by karentom** [comment]
Tested and works.
