### ISSUE TITLE
All Pending Partners section in Employee Dashboard should not list all partners

### ISSUE THREAD

**Issue by karentom** [springernature/snics-employee#122]
Pending Partners should exclude  "Completed", "Reviewed" and "Do Not Use" statuses.

Right now it is displaying all partners.

![image](https://user-images.githubusercontent.com/17595871/51336680-2b258e00-1a53-11e9-8d00-25b55f53e47e.png)

**Comment by mohammadsiddiqui** [comment]
Also add Expired in exclusion for pending partner List.

**Comment by harshadporwal** [comment]
![image](https://user-images.githubusercontent.com/43807299/51653010-9de4bb00-1fb7-11e9-8ccf-a611cbf015c0.png)

Added in API and removed filter expired from filter dropdown.

**Comment by karentom** [comment]
tested in UAT and works.
