### ISSUE TITLE
Not Submitted filter is not working

### ISSUE THREAD

**Issue by karentom** [springernature/snics-employee#123]
Nothing appears when you click on "Not Submitted" button.

![image](https://user-images.githubusercontent.com/17595871/51337146-5f4d7e80-1a54-11e9-88b7-6519fbd69139.png)

**Comment by harshadporwal** [comment]
![image](https://user-images.githubusercontent.com/43807299/51370548-858b2100-1b1d-11e9-8305-9a7af10593f6.png)

Fixed and working

**Comment by karentom** [comment]
Tested in UAT and works.
