### ISSUE TITLE
Remove columns from Assessments section

### ISSUE THREAD

**Issue by karentom** [springernature/snics-employee#124]
'Name of internal owner' and 'Territory of internal owner' columns are not needed in the Employee portal

![image](https://user-images.githubusercontent.com/17595871/51337903-61184180-1a56-11e9-95f3-ad46d17d843f.png)

In current system, those columns are not there.
![image](https://user-images.githubusercontent.com/17595871/51337930-72614e00-1a56-11e9-82fe-f8121cf2517c.png)

**Comment by harshadporwal** [comment]
![image](https://user-images.githubusercontent.com/43807299/51366005-4357e480-1b09-11e9-8e46-2641dc3e3f22.png)

Removed unwanted coulmns.
