### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by harshadporwal** [springernature/snics-employee#191]

**Comment by karentom** [comment]
In management labels, ‘Legal Entry’ typo needs to be changed to ‘Legal Entity’. Typo also appears in the URL and needs to be fixed.

![image](https://user-images.githubusercontent.com/17595871/54710571-5c3b4100-4b1e-11e9-89a8-8a8f8a03c322.png)

![image](https://user-images.githubusercontent.com/17595871/54710692-9e648280-4b1e-11e9-8219-d5c2f664874c.png)

**Comment by harshadporwal** [comment]
@karentom Fixed and working in UAT

![image](https://user-images.githubusercontent.com/43807299/54822037-f5f32180-4cc9-11e9-919f-290b2f217c68.png)

**Comment by karentom** [comment]
@harshadporwal There is still a type in the URL

![image](https://user-images.githubusercontent.com/17595871/54890680-cf2b1b80-4e80-11e9-9f24-13a7a6dc7601.png)

**Comment by harshadporwal** [comment]
@karentom the changes are not moved to LIVE yet. Should I deploy all the changes to LIVE?

**Comment by karentom** [comment]
@harshadporwal Thanks for fixing the typo. Checked the live URL and is fine.

**Comment by mirellasprenger** [comment]
SNICS is available in English, portuguese, german and spanish. 

[RE_ Language support - Live.pdf](https://github.com/springernature/snics-employee/files/3038520/RE_.Language.support.-.Live.pdf)
