### ISSUE TITLE
Error on BP creation on SAP

### ISSUE THREAD

**Issue by mirellasprenger** [springernature/snics-employee#222]
Please check the interface on creating BP on SAP.

![image](https://user-images.githubusercontent.com/43644896/53945762-9b02dd00-40c2-11e9-8a5f-ce23f4bfc826.png)

**Comment by karentom** [comment]
@harshadporwal @mirellasprenger We should add comments here if the issue is fixed and/or tested so that they can be closed if they are fixed. I believe based on the emails that this issue is fixed and can be closed?

**Comment by harshadporwal** [comment]
@karentom The user reported again the same issue today. The issue was with the length of the fields supported in SAP. I have fixed the issue for now. Let us wait for sometime and check if the user comebacks with the issue again or otherwise we will close it

**Comment by karentom** [comment]
Tested and closing.
