### ISSUE TITLE
Update the status for a "Not Yet Invited" if the partner is not on SNICS

### ISSUE THREAD

**Issue by mirellasprenger** [springernature/snics-employee#234]
Email attached.

![image](https://user-images.githubusercontent.com/43644896/54130929-a0895b80-4411-11e9-9d9b-928aa3ad31fc.png)

**Comment by harshadporwal** [comment]
@mirellasprenger Issue fixed. Please test it in UAT and let us know if everything Ok will move it to LIVE

**Comment by karentom** [comment]
Tested and works.
