### ISSUE TITLE
Mexico distributors for deletion

### ISSUE THREAD

**Issue by karentom** [springernature/snics-employee#235]
The red rows in the attached are not needed in SNICS any longer according to the Mexican entity. Please could you kindly arrange for them to be removed from SNICS?

[SNICS Report - 19feb2019.xlsx](https://github.com/springernature/snics-employee/files/2954538/SNICS.Report.-.19feb2019.xlsx)

**Comment by harshadporwal** [comment]
@karentom I have created the endpoint for deleting records from SNICS. So can I go ahead and delete it from LIVE system?

**Comment by karentom** [comment]
Yes, the records highlighted in the file can be deleted.

**Comment by harshadporwal** [comment]
@karentom The record highlighted are deleted from database
