### ISSUE TITLE
Status info box

### ISSUE THREAD

**Issue by karentom** [springernature/snics-employee#267]
A status info box is needed explain the status definitions. Next to status, there should be an i icon for information button where there is a status column. There are 2 in the employee portal.

![image](https://user-images.githubusercontent.com/17595871/54966911-1af6c700-4f4c-11e9-906f-d1ea69db727a.png)

![image](https://user-images.githubusercontent.com/17595871/54966931-29dd7980-4f4c-11e9-81fb-c6773ac26784.png)

The info box should contain the following information:

![image](https://user-images.githubusercontent.com/17595871/54966957-437ec100-4f4c-11e9-89b3-b6dd98f7a784.png)

**Comment by harshadporwal** [comment]
@karentom Added status info box. Please test it in UAT

**Comment by karentom** [comment]
@harshadporwal Can we add an icon for users to click into? It is not clear that the 'Status' text is clickable. I knew about it and it took me a few secs to realize I had to click on the text.

For example an icon like the one below and make that clickable?
![image](https://user-images.githubusercontent.com/17595871/55890796-5a92f500-5b81-11e9-8e5c-65d059912ef9.png)

**Comment by harshadporwal** [comment]
@karentom Added the icon beside "Status" label

**Comment by karentom** [comment]
@harshadporwal looks great!
