### ISSUE TITLE
Renewal date of risk review is different between the management and employee portals

### ISSUE THREAD

**Issue by karentom** [springernature/snics-employee#291]
I updated the date of the renewal date of risk review in the management portal to 7/9/2019. I checked the record for that assessment in the employee portal and the renewal date does not match.

![image](https://user-images.githubusercontent.com/17595871/55906807-19abd800-5ba3-11e9-8e03-730123967df3.png)

**Comment by karentom** [comment]
I think this may be a display issue. It is displaying DD/MM/YYYY in the employee portal and it seems the time zone issue is there in the employee portal.  In the management portal, the date displays as MM/DD/YYYY and the date is the correct date.

**Comment by karentom** [comment]
I added a contract and it confirms my comment above. The issue also appears for the renewal date of contract.

**Comment by harshadporwal** [comment]
@karentom Fixed date wherever required. Please test and let me know if the issue still exist.

**Comment by karentom** [comment]
@harshadporwal looks good
