### ISSUE TITLE
Uploaded documents not being displayed

### ISSUE THREAD

**Issue by karentom** [springernature/snics-employee#292]
I uploaded a contract and in the employee portal, it is not displaying in the document section. It displays fine in the management portal.

![image](https://user-images.githubusercontent.com/17595871/55908402-5e397280-5ba7-11e9-8995-98e4427cbf05.png)

**Comment by harshadporwal** [comment]
@karentom Issue is fixed. Please test in UAT

**Comment by karentom** [comment]
@harshadporwal Fixed.
