### ISSUE TITLE
Status Info Box Translations

### ISSUE THREAD

**Issue by karentom** [springernature/snics-employee#301]
The Status Info box needs to be translated. (From Steph's email 4/17/2019)

![image](https://user-images.githubusercontent.com/17595871/56426930-0629fc80-6288-11e9-9eb5-d32acaf45640.png)

![image](https://user-images.githubusercontent.com/17595871/56426943-15a94580-6288-11e9-954c-5c2f5fb1afc6.png)

**Comment by karentom** [comment]
Spanish translation completed

![image](https://user-images.githubusercontent.com/17595871/56426988-3ec9d600-6288-11e9-9df9-c6edd5df1318.png)

**Comment by harshadporwal** [comment]
@karentom Status box translation can be updated from language translation functionality in managment portal in the lable section of Employee-Lablels

**Comment by mirellasprenger** [comment]
All the translations were double checked and updated on the Language support functionality.
Email attached.
@karentom May l I close this ticket? 

[RE_ SNICS status translations.pdf](https://github.com/springernature/snics-employee/files/3141408/RE_.SNICS.status.translations.pdf)

**Comment by karentom** [comment]
@mirellasprenger Good to close. I'll remind Steph to add the Spanish translations.
